toml[build]
  base = ""
  publish = "."
  functions = "netlify/functions"
  command = "npm install"

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/signup.html"
  status = 200